# Rideshare API Server Configuration

server:
  port: "8080"  # Port to listen on
  read_timeout: 30  # Read timeout in seconds
  write_timeout: 30  # Write timeout in seconds
  log_level: "info"  # Log level (debug, info, warn, error)

database:
  primary:  # Primary database (for writes)
    host: "localhost"  # Use db-primary in production
    port: "5432"
    user: "postgres"
    password: "postgres123"
    dbname: "rideshare"
    sslmode: "disable"  # Use "require" in production
  
  # Read replicas (for read scaling)
  replicas:
    - host: "localhost"  # Use db-replica1 in production
      port: "5432"
      user: "postgres" 
      password: "postgres123"
      dbname: "rideshare"
      sslmode: "disable"
  
  # Connection pool settings
  max_open_conns: 25  # Maximum number of open connections
  max_idle_conns: 5   # Maximum number of idle connections
  conn_max_lifetime: 300  # Connection max lifetime in seconds (5 minutes)